name: Linter

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13 
      uses: actions/setup-python@v3
      with:
        python-version: 3.13 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 
    - name: Analysing code with Flake8 
      run: |
        flake8 . 
  
  type:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13 
      uses: actions/setup-python@v3
      with:
        python-version: 3.13 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy 
    - name: Type checking code with Mypy 
      run: |
        mypy gateway/ 


